### ISSUE TITLE
fix: CoreDNS image cannot be pulled when use custom registry as kubernetes_image_repository

### ISSUE THREAD

**Issue by cuttingedge1109** [vexxhost/ansible-collection-kubernetes#30]
https://github.com/kubernetes/kubeadm/issues/2714

**Comment by mnaser** [comment]
@cuttingedge1109: thanks for the bug report, I think we already have use cases where we are actually accomodating for the fact that coredns images are all at a weird path.

since it would be an api breaking change if we made that change, do you think you it makes sense for us to have overrides available instead so you can override the kubeadm config?

**Comment by cuttingedge1109** [comment]
> a

yeap, that will work also

**Comment by mnaser** [comment]
@cuttingedge1109 I believe this shouldn't be needed now cause all images will have that direct path under the `kubernetes_image_repository` -- so I think you should be good to g?

**Comment by cuttingedge1109** [comment]
> @cuttingedge1109 I believe this shouldn't be needed now cause all images will have that direct path under the `kubernetes_image_repository` -- so I think you should be good to g?

@mnaser sorry for my late response.
I suggest setting coredns repository explicitly with subpath respecting the kubernetes official document. It worked well for our all private clusters. Here is a pull request. 
https://github.com/vexxhost/ansible-collection-kubernetes/pull/66
